package com.template.app.update

import android.content.Context
import com.template.app.AppConfig
import com.template.app.security.SecureKeyManager
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

/**
 * Hilt module that provides the [AppUpdateManager] singleton.
 *
 * Reads [AppConfig.GITHUB_RELEASES_REPO_OWNER] and [AppConfig.GITHUB_RELEASES_REPO_NAME]
 * so that the repository checked for new release APKs is configured in one central place.
 * This can be the same repo as [AppConfig.GITHUB_ISSUES_REPO_NAME] or a separate one
 * (e.g. a dedicated distribution/releases repo).
 *
 * To change where updates are fetched from, update [AppConfig] — do not edit this file.
 */
@Module
@InstallIn(SingletonComponent::class)
object AppUpdateManagerModule {

    @Provides
    @Singleton
    fun provideAppUpdateManager(
        @ApplicationContext context: Context,
        secureKeyManager: SecureKeyManager
    ): AppUpdateManager {
        return AppUpdateManager(
            context = context,
            secureKeyManager = secureKeyManager,
            repoOwner = AppConfig.GITHUB_RELEASES_REPO_OWNER,
            repoName = AppConfig.GITHUB_RELEASES_REPO_NAME
        )
    }
}
