package com.template.app.bugreport

import com.template.app.AppConfig
import com.template.app.security.SecureKeyManager
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

/**
 * Hilt module that provides the [GitHubIssuesClient] singleton.
 *
 * Reads [AppConfig.GITHUB_ISSUES_REPO_OWNER] and [AppConfig.GITHUB_ISSUES_REPO_NAME]
 * so that the repository target for bug reports is configured in one central place.
 *
 * To change where bug reports are submitted, update [AppConfig] — do not edit this file.
 */
@Module
@InstallIn(SingletonComponent::class)
object GitHubIssuesClientModule {

    @Provides
    @Singleton
    fun provideGitHubIssuesClient(
        secureKeyManager: SecureKeyManager
    ): GitHubIssuesClient {
        return GitHubIssuesClient(
            secureKeyManager = secureKeyManager,
            repoOwner = AppConfig.GITHUB_ISSUES_REPO_OWNER,
            repoName = AppConfig.GITHUB_ISSUES_REPO_NAME
        )
    }
}
