package com.mylock.app

/**
 * Central per-app configuration object.
 *
 * This is the **single file to update** when creating a new Android app from this template.
 * All infrastructure files read their configurable values from here, so changing them here
 * is sufficient — no need to hunt through multiple modules.
 *
 * ## GitHub repositories
 * The template supports up to three separate GitHub repositories (they can all point to the
 * same repo if you prefer simplicity):
 *
 * | Constant group | Purpose |
 * |---------------|---------|
 * | `GITHUB_ISSUES_*` | Where [bugreport.GitHubIssuesClient] submits bug report issues and uploads screenshots |
 * | `GITHUB_RELEASES_*` | Where [update.AppUpdateManager] looks for new release APKs |
 *
 * ## Other settings
 * - [APP_NAME]: used in backup filenames and the settings screen.
 * - [SECURE_PREFS_FILENAME]: the on-disk filename for the encrypted key store.
 *   **Do not change after shipping** — existing users will lose their stored keys.
 *
 * ## Quick start
 * Run `./setup_new_app.sh` to patch this file and `build.gradle.kts` / `strings.xml`
 * interactively instead of editing manually.
 */
object AppConfig {

    // -----------------------------------------------------------------------------------------
    // Bug Reports — GitHub repository where issues and screenshots are submitted
    // Used by: bugreport.GitHubIssuesClient, bugreport.GitHubIssuesClientModule
    // -----------------------------------------------------------------------------------------

    /** GitHub username or organization that owns the bug-report / issues repository. TODO: Change this. */
    const val GITHUB_ISSUES_REPO_OWNER = "itsikh"

    /**
     * GitHub repository name where bug report issues are created and screenshots are uploaded.
     * The GitHub token stored under [security.SecureKeyManager] key
     * [bugreport.GitHubIssuesClient.KEY_GITHUB_TOKEN] must have write access to this repo.
     */
    const val GITHUB_ISSUES_REPO_NAME = "mylock"

    // -----------------------------------------------------------------------------------------
    // App Updates — GitHub repository where release APKs are published
    // Used by: update.AppUpdateManager, update.AppUpdateManagerModule
    // Can be the same as the issues repo or a different one (e.g. a dedicated releases repo).
    // -----------------------------------------------------------------------------------------

    /** GitHub username or organization that owns the releases repository. */
    const val GITHUB_RELEASES_REPO_OWNER = "itsikh"

    /**
     * GitHub repository name where GitHub Releases with APK assets are published.
     * [update.AppUpdateManager] fetches the latest release tag from this repo and compares
     * it against the running [BuildConfig.VERSION_NAME] to decide if an update is available.
     */
    const val GITHUB_RELEASES_REPO_NAME = "mylock"

    // -----------------------------------------------------------------------------------------
    // General
    // -----------------------------------------------------------------------------------------

    /**
     * Human-readable app name used in:
     * - Backup filenames generated by [backup.BaseBackupManager] and [backup.BaseSettingsBackupManager]
     * - The "About" section in [ui.components.SettingsScaffold]
     *
     * This is separate from `res/values/strings.xml` → `app_name`, which controls the
     * launcher icon label and window title.
     * TODO: Change this.
     */
    const val APP_NAME = "MyLock"

    /**
     * Filename for the encrypted SharedPreferences file managed by [security.SecureKeyManager].
     * **Only rename this before the first public release.** Changing this value on an existing
     * install causes all previously stored secure keys (GitHub token, API keys, etc.) to be
     * inaccessible, because the old encrypted file will not be found.
     * TODO: Rename to match your app.
     */
    const val SECURE_PREFS_FILENAME = "mylock_secure_keys"

    // -----------------------------------------------------------------------------------------
    // TTLock — Developer app credentials (from TTLock open platform)
    // These are app-level credentials, NOT the user's TTLock account credentials.
    // User credentials (username + password) are entered in-app and stored encrypted.
    // -----------------------------------------------------------------------------------------

    /**
     * TTLock developer client ID from https://euopen.ttlock.com/
     * Fill this in before building. Safe to bake into the APK (it's not a secret).
     */
    const val TTLOCK_CLIENT_ID = "9c5fb400ea02452ba890826f3c67545d"

    /**
     * TTLock developer client secret. Also from the open platform dashboard.
     * This is hashed (MD5) before every API call, but still treat it with care.
     */
    const val TTLOCK_CLIENT_SECRET = "76628a9fc3165c7b058493b25da0251b"

    // -----------------------------------------------------------------------------------------
    // Geofencing
    // -----------------------------------------------------------------------------------------

    /** Radius in meters around home location within which the widget unlock button is enabled. */
    const val HOME_GEOFENCE_RADIUS_METERS = 100f

    /** Notification channel ID for geofence transition alerts. */
    const val NOTIFICATION_CHANNEL_GEOFENCE = "channel_geofence"

    // -----------------------------------------------------------------------------------------
    // Notifications
    // -----------------------------------------------------------------------------------------

    /**
     * Notification channel ID used by [backup.BaseBackupManager] when posting the
     * "Backup ready — tap to save" notification that triggers [backup.BackupSaveActivity].
     * Must match the channel created in [TemplateApplication.onCreate].
     */
    const val NOTIFICATION_CHANNEL_BACKUP = "channel_backup"
}
